apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app-of-projects
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-12"
spec:  
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: argocd
  source:
    repoURL: https://github.com/AATT_GITHUB_USERNAME/automate-all-the-things-transcendence.git # This value was modified by the initial-setup python script
    path: argo-cd/self-manage/appprojects
    directory:
      recurse: true
      jsonnet: {}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
