apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # Adding the finalizer enables cascading deletes when implementing the App of Apps pattern. If this isn't used, when you remove the application yaml from git, the application will be removed from ArgoCD but the resources will remain active in the cluster
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc  
  project: observability
  source:
    path: helm-charts/infra/grafana
    helm:
      valueFiles:
        - values-custom.yaml
    repoURL: https://github.com/AATT_DOCKERHUB_USERNAME/automate-all-the-things-transcendence.git # This value was modified by the initial-setup python script
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true # Required because of error "Too long: must have at most 262144 bytes." 
