apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.system }}-${{ values.service }}-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # Adding the finalizer enables cascading deletes when implementing the App of Apps pattern. If this isn't used, when you remove the application yaml from git, the application will be removed from ArgoCD but the resources will remain active in the cluster
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: ${{ values.system }}-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm-charts/systems/${{ values.system }}/${{ values.service }}
    helm:
      valueFiles:
        - environments/values-dev.yaml
    repoURL: https://github.com/AATT_DOCKERHUB_USERNAME/automate-all-the-things-transcendence.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      # labels:
      #   istio-injection: enabled
